Models/CategoriesTraductions.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ProjetEpîcerie.Models
{
    public class CategoriesTraductions
    {

        //Relation avec Categorie
        public int IdCategorie { get; set; }
        public virtual Categorie Categorie { get; set; }

        [Key]
        public int IdCategoriesTraductions { get; set; }
        [Required]
        public string NameTraduction { get; set; }
        [Required]
        public string DescriptionTraduction { get; set; }

        //Relation avec langue
        public int IdLangue { get; set; }
        public virtual Langue Langue { get; set; }



    }
}

Controllers/CategoriesTraductionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProjetEpîcerie.Models;

namespace ProjetEpîcerie.Controllers
{
    public class CategoriesTraductionsController : Controller
    {
        private SamiDb db = new SamiDb();

        // GET: CategoriesTraductions
        public ActionResult Index()
        {
            var categoriesTraductions = db.CategoriesTraductions.Include(c => c.Categorie).Include(c => c.Langue);
            return View(categoriesTraductions.ToList());
        }

        // GET: CategoriesTraductions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CategoriesTraductions categoriesTraductions = db.CategoriesTraductions.Find(id);
            if (categoriesTraductions == null)
            {
                return HttpNotFound();
            }
            return View(categoriesTraductions);
        }

        // GET: CategoriesTraductions/Create
        public ActionResult Create()
        {
            ViewBag.IdCategorie = new SelectList(db.Categories, "IdCategorie", "Name");
            ViewBag.IdLangue = new SelectList(db.Langues, "IdLangue", "Description");
            return View();
        }

        // POST: CategoriesTraductions/Create
        // Pour vous protéger des attaques par survalidation, activez les propriétés spécifiques auxquelles vous souhaitez vous lier. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdCategoriesTraductions,IdCategorie,NameTraduction,DescriptionTraduction,IdLangue")] CategoriesTraductions categoriesTraductions)
        {
            if (ModelState.IsValid)
            {
                db.CategoriesTraductions.Add(categoriesTraductions);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.IdCategorie = new SelectList(db.Categories, "IdCategorie", "Name", categoriesTraductions.IdCategorie);
            ViewBag.IdLangue = new SelectList(db.Langues, "IdLangue", "Description", categoriesTraductions.IdLangue);
            return View(categoriesTraductions);
        }

        // GET: CategoriesTraductions/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CategoriesTraductions categoriesTraductions = db.CategoriesTraductions.Find(id);
            if (categoriesTraductions == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdCategorie = new SelectList(db.Categories, "IdCategorie", "Name", categoriesTraductions.IdCategorie);
            ViewBag.IdLangue = new SelectList(db.Langues, "IdLangue", "Description", categoriesTraductions.IdLangue);
            return View(categoriesTraductions);
        }

        // POST: CategoriesTraductions/Edit/5
        // Pour vous protéger des attaques par survalidation, activez les propriétés spécifiques auxquelles vous souhaitez vous lier. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdCategoriesTraductions,IdCategorie,NameTraduction,DescriptionTraduction,IdLangue")] CategoriesTraductions categoriesTraductions)
        {
            if (ModelState.IsValid)
            {
                db.Entry(categoriesTraductions).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IdCategorie = new SelectList(db.Categories, "IdCategorie", "Name", categoriesTraductions.IdCategorie);
            ViewBag.IdLangue = new SelectList(db.Langues, "IdLangue", "Description", categoriesTraductions.IdLangue);
            return View(categoriesTraductions);
        }

        // GET: CategoriesTraductions/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CategoriesTraductions categoriesTraductions = db.CategoriesTraductions.Find(id);
            if (categoriesTraductions == null)
            {
                return HttpNotFound();
            }
            return View(categoriesTraductions);
        }

        // POST: CategoriesTraductions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CategoriesTraductions categoriesTraductions = db.CategoriesTraductions.Find(id);
            db.CategoriesTraductions.Remove(categoriesTraductions);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/LanguesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProjetEpîcerie.Models;

namespace ProjetEpîcerie.Controllers
{
    public class LanguesController : Controller
    {
        private SamiDb db = new SamiDb();

        // GET: Langues
        public ActionResult Index()
        {
            return View(db.Langues.ToList());
        }

        // GET: Langues/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Langue langue = db.Langues.Find(id);
            if (langue == null)
            {
                return HttpNotFound();
            }
            return View(langue);
        }

        // GET: Langues/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Langues/Create
        // Pour vous protéger des attaques par survalidation, activez les propriétés spécifiques auxquelles vous souhaitez vous lier. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdLangue,Description,Symbole")] Langue langue)
        {
            if (ModelState.IsValid)
            {
                db.Langues.Add(langue);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(langue);
        }

        // GET: Langues/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Langue langue = db.Langues.Find(id);
            if (langue == null)
            {
                return HttpNotFound();
            }
            return View(langue);
        }

        // POST: Langues/Edit/5
        // Pour vous protéger des attaques par survalidation, activez les propriétés spécifiques auxquelles vous souhaitez vous lier. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdLangue,Description,Symbole")] Langue langue)
        {
            if (ModelState.IsValid)
            {
                db.Entry(langue).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(langue);
        }

        // GET: Langues/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Langue langue = db.Langues.Find(id);
            if (langue == null)
            {
                return HttpNotFound();
            }
            return View(langue);
        }

        // POST: Langues/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Langue langue = db.Langues.Find(id);
            db.Langues.Remove(langue);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/PaniersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProjetEpîcerie.Models;

namespace ProjetEpîcerie.Controllers
{
    public class PaniersController : Controller
    {
        private SamiDb db = new SamiDb();

        // GET: Paniers
        public ActionResult Index()
        {
            var paniers = db.Paniers.Include(p => p.Produits).Include(p => p.Utilisateur);
            return View(paniers.ToList());
        }

        // GET: Paniers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Panier panier = db.Paniers.Find(id);
            if (panier == null)
            {
                return HttpNotFound();
            }
            return View(panier);
        }

        // GET: Paniers/Create
        public ActionResult Create()
        {
            ViewBag.IdProduits = new SelectList(db.Produits, "IdProduits", "Nom");
            ViewBag.IdUtilisateur = new SelectList(db.Utilisateur, "IdUtilisateur", "Name");
            return View();
        }

        // POST: Paniers/Create
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdPanier,Quantité,IdUtilisateur,IdProduits")] Panier panier)
        {
            if (ModelState.IsValid)
            {
                db.Paniers.Add(panier);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.IdProduits = new SelectList(db.Produits, "IdProduits", "Nom", panier.IdProduits);
            ViewBag.IdUtilisateur = new SelectList(db.Utilisateur, "IdUtilisateur", "Name", panier.IdUtilisateur);
            return View(panier);
        }

        // GET: Paniers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Panier panier = db.Paniers.Find(id);
            if (panier == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdProduits = new SelectList(db.Produits, "IdProduits", "Nom", panier.IdProduits);
            ViewBag.IdUtilisateur = new SelectList(db.Utilisateur, "IdUtilisateur", "Name", panier.IdUtilisateur);
            return View(panier);
        }

        // POST: Paniers/Edit/5
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdPanier,Quantité,IdUtilisateur,IdProduits")] Panier panier)
        {
            if (ModelState.IsValid)
            {
                db.Entry(panier).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IdProduits = new SelectList(db.Produits, "IdProduits", "Nom", panier.IdProduits);
            ViewBag.IdUtilisateur = new SelectList(db.Utilisateur, "IdUtilisateur", "Name", panier.IdUtilisateur);
            return View(panier);
        }

        // GET: Paniers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Panier panier = db.Paniers.Find(id);
            if (panier == null)
            {
                return HttpNotFound();
            }
            return View(panier);
        }

        // POST: Paniers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Panier panier = db.Paniers.Find(id);
            db.Paniers.Remove(panier);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/CategoriesTraductions/Create.cshtml
@model ProjetEpîcerie.Models.CategoriesTraductions

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CategoriesTraductions</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.IdCategorie, "IdCategorie", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdCategorie", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdCategorie, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NameTraduction, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NameTraduction, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NameTraduction, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DescriptionTraduction, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DescriptionTraduction, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DescriptionTraduction, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdLangue, "IdLangue", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdLangue", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdLangue, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Views/CategoriesTraductions/Delete.cshtml
@model ProjetEpîcerie.Models.CategoriesTraductions

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CategoriesTraductions</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Categorie.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Categorie.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Langue.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Langue.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NameTraduction)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NameTraduction)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DescriptionTraduction)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DescriptionTraduction)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/CategoriesTraductions/Details.cshtml
@model ProjetEpîcerie.Models.CategoriesTraductions

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>CategoriesTraductions</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Categorie.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Categorie.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Langue.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Langue.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NameTraduction)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NameTraduction)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DescriptionTraduction)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DescriptionTraduction)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.IdCategoriesTraductions }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/CategoriesTraductions/Edit.cshtml
@model ProjetEpîcerie.Models.CategoriesTraductions

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CategoriesTraductions</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IdCategoriesTraductions)

        <div class="form-group">
            @Html.LabelFor(model => model.IdCategorie, "IdCategorie", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdCategorie", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdCategorie, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NameTraduction, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NameTraduction, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NameTraduction, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DescriptionTraduction, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DescriptionTraduction, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DescriptionTraduction, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdLangue, "IdLangue", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdLangue", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdLangue, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Views/CategoriesTraductions/Index.cshtml
@model IEnumerable<ProjetEpîcerie.Models.CategoriesTraductions>
<link href="~/Css/Acceuil.css" rel="stylesheet" />
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">

<header>
    <nav class="navbar navbar-expand-sm bg-white navbar-dark">
        <div class="container-fluid">

            <a class="navbar-brand" href="#">
                <img src="../image/logo3.jpg" alt="logo" style="width: 100px; height: auto;">
            </a>

            <span id="txtLogo" style="font-size:21px">  TEC-EPICFARMERS MARKET
            <div class="collapse navbar-collapse" id="collapsibleNavbar">
                <ul class="navbar-nav">
                    <li>
                        <a href="@Url.Action("Index", "Categories")" class="btn btn-primary">Catégories</a>
                    </li>
                    <li style="margin-left:10px">
                        <a href="@Url.Action("Index", "CategoriesTraductions")" class="btn btn-primary">Catégories Traductions</a>
                    </li>
                    <li style="margin-left:10px">
                        <a href="@Url.Action("Index", "Langues")" class="btn btn-primary"> Langues</a>
                    </li>
                    <li style="margin-left:10px">
                        <a href="@Url.Action("Index", "Paniers")" class="btn btn-primary"> Paniers</a>
                    </li>
                    <li style="margin-left:10px">
                        <a href="@Url.Action("Index", "Produits")" class="btn btn-primary"> Produits</a>
                    </li>
                    <li style="margin-left:10px">
                        <a href="@Url.Action("Index", "ProduitsTraductions")" class="btn btn-primary"> Produits Traductions</a>
                    </li>
      
                    <li style="margin-left:10px">
                        <a href="@Url.Action("Deconnexion", "Default")" class="btn btn-primary"> Deconnexion</a>
                    </li>

                </ul>

            </div>

        </div>
    </nav>
</header>
<div class="div1">
    <p class="titrePage">
        Liste des Traductions des Categories
    </p>
</div>
<p>
    <a href="@Url.Action("Create", "CategoriesTraductions")"> Create new</a>
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Categorie.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Langue.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NameTraduction)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DescriptionTraduction)
        </th>
        <th>
            Actions
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Categorie.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Langue.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NameTraduction)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DescriptionTraduction)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.IdCategoriesTraductions }) |
                @Html.ActionLink("Details", "Details", new { id = item.IdCategoriesTraductions }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.IdCategoriesTraductions })
            </td>
        </tr>
    }

</table>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>