Models/Produits.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace ProjetEpîcerie.Models
{
    public class Produits
    {
        //Relation avec langue
        public int IdLangue { get; set; }
        public virtual Langue Langue { get; set; }


        //Relation avec categorie
        public int IdCategorie { get; set; }
        public virtual Categorie Categorie { get; set; }

        [Key]
        public int IdProduits{ get; set; }
        [Required]
        public string Nom { get; set; }
        [Required]
        public string Description { get; set; }
        [Required]
        public float Prix { get; set; }

        public string urlImage { get; set; }

        //Relation avec ProduitsTraductions
        public virtual List<ProduitsTraductions> ProduitsTraductions { get; set; }



    }
}

Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProjetEpîcerie.Models;

namespace ProjetEpîcerie.Controllers
{
    public class CategoriesController : Controller
    {
        private SamiDb db = new SamiDb();

        // GET: Categories
        public ActionResult Index()
        {
            var categories = db.Categories.Include(c => c.Langue);
            return View(categories.ToList());
        }

        // GET: Categories/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Categorie categorie = db.Categories.Find(id);
            if (categorie == null)
            {
                return HttpNotFound();
            }
            return View(categorie);
        }

        // GET: Categories/Create
        public ActionResult Create()
        {
            ViewBag.IdLangue = new SelectList(db.Langues, "IdLangue", "Description");
            return View();
        }

        // POST: Categories/Create
        // Pour vous protéger des attaques par survalidation, activez les propriétés spécifiques auxquelles vous souhaitez vous lier. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdCategorie,IdLangue,Name,Description")] Categorie categorie)
        {
            if (ModelState.IsValid)
            {
                db.Categories.Add(categorie);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.IdLangue = new SelectList(db.Langues, "IdLangue", "Description", categorie.IdLangue);
            return View(categorie);
        }

        // GET: Categories/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Categorie categorie = db.Categories.Find(id);
            if (categorie == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdLangue = new SelectList(db.Langues, "IdLangue", "Description", categorie.IdLangue);
            return View(categorie);
        }

        // POST: Categories/Edit/5
        // Pour vous protéger des attaques par survalidation, activez les propriétés spécifiques auxquelles vous souhaitez vous lier. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdCategorie,IdLangue,Name,Description")] Categorie categorie)
        {
            if (ModelState.IsValid)
            {
                db.Entry(categorie).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IdLangue = new SelectList(db.Langues, "IdLangue", "Description", categorie.IdLangue);
            return View(categorie);
        }

        // GET: Categories/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Categorie categorie = db.Categories.Find(id);
            if (categorie == null)
            {
                return HttpNotFound();
            }
            return View(categorie);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Categorie categorie = db.Categories.Find(id);
            db.Categories.Remove(categorie);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult Acceuil(int? id)
        {
            string username = Session["username"].ToString();
            string password = Session["password"].ToString();
            var listLangue = db.Langues.ToList();
            ViewBag.Langue = listLangue;

            int idDefault = 1;

            if (id == null)
            {
                Session["Idlangue"] = idDefault;
                return View(db.Categories.Where(m => m.IdLangue == idDefault).ToList());
            }
            else if (id == 1)
            {
                return View(db.Categories.Where(m => m.IdLangue == idDefault).ToList());

            }
            else
            {
                Session["Idlangue"] = id;
                var listTraduction = db.CategoriesTraductions.Where(m => m.IdLangue == id).ToList();
                List<Categorie> categories = new List<Categorie>();
    

                foreach (var traduction in listTraduction)
                {
                    Categorie Cat = new Categorie(); 
                    Cat.IdLangue = traduction.IdLangue;
                    Cat.Name = traduction.NameTraduction;
                    Cat.Description = traduction.DescriptionTraduction;
                    categories.Add(Cat);
                }

                return View(categories);
            }
        }

    }
}

Controllers/LanguesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProjetEpîcerie.Models;

namespace ProjetEpîcerie.Controllers
{
    public class LanguesController : Controller
    {
        private SamiDb db = new SamiDb();

        // GET: Langues
        public ActionResult Index()
        {
            return View(db.Langues.ToList());
        }

        // GET: Langues/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Langue langue = db.Langues.Find(id);
            if (langue == null)
            {
                return HttpNotFound();
            }
            return View(langue);
        }

        // GET: Langues/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Langues/Create
        // Pour vous protéger des attaques par survalidation, activez les propriétés spécifiques auxquelles vous souhaitez vous lier. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdLangue,Description,Symbole")] Langue langue)
        {
            if (ModelState.IsValid)
            {
                db.Langues.Add(langue);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(langue);
        }

        // GET: Langues/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Langue langue = db.Langues.Find(id);
            if (langue == null)
            {
                return HttpNotFound();
            }
            return View(langue);
        }

        // POST: Langues/Edit/5
        // Pour vous protéger des attaques par survalidation, activez les propriétés spécifiques auxquelles vous souhaitez vous lier. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdLangue,Description,Symbole")] Langue langue)
        {
            if (ModelState.IsValid)
            {
                db.Entry(langue).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(langue);
        }

        // GET: Langues/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Langue langue = db.Langues.Find(id);
            if (langue == null)
            {
                return HttpNotFound();
            }
            return View(langue);
        }

        // POST: Langues/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Langue langue = db.Langues.Find(id);
            db.Langues.Remove(langue);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/ProduitsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProjetEpîcerie.Models;

namespace ProjetEpîcerie.Controllers
{
    public class ProduitsController : Controller
    {
        private SamiDb db = new SamiDb();

        // GET: Produits
        public ActionResult Index()
        {
            var produits = db.Produits.Include(p => p.Categorie).Include(p => p.Langue);
            return View(produits.ToList());
        }

        // GET: Produits/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Produits produits = db.Produits.Find(id);
            if (produits == null)
            {
                return HttpNotFound();
            }
            return View(produits);
        }

        // GET: Produits/Create
        public ActionResult Create()
        {
            ViewBag.IdCategorie = new SelectList(db.Categories, "IdCategorie", "Name");
            ViewBag.IdLangue = new SelectList(db.Langues, "IdLangue", "Description");
            return View();
        }

        // POST: Produits/Create
        // Pour vous protéger des attaques par survalidation, activez les propriétés spécifiques auxquelles vous souhaitez vous lier. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdProduits,IdLangue,IdCategorie,Nom,Description,Prix,urlImage")] Produits produits)
        {
            if (ModelState.IsValid)
            {
                db.Produits.Add(produits);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.IdCategorie = new SelectList(db.Categories, "IdCategorie", "Name", produits.IdCategorie);
            ViewBag.IdLangue = new SelectList(db.Langues, "IdLangue", "Description", produits.IdLangue);
            return View(produits);
        }

        // GET: Produits/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Produits produits = db.Produits.Find(id);
            if (produits == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdCategorie = new SelectList(db.Categories, "IdCategorie", "Name", produits.IdCategorie);
            ViewBag.IdLangue = new SelectList(db.Langues, "IdLangue", "Description", produits.IdLangue);
            return View(produits);
        }

        // POST: Produits/Edit/5
        // Pour vous protéger des attaques par survalidation, activez les propriétés spécifiques auxquelles vous souhaitez vous lier. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdProduits,IdLangue,IdCategorie,Nom,Description,Prix,urlImage")] Produits produits)
        {
            if (ModelState.IsValid)
            {
                db.Entry(produits).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IdCategorie = new SelectList(db.Categories, "IdCategorie", "Name", produits.IdCategorie);
            ViewBag.IdLangue = new SelectList(db.Langues, "IdLangue", "Description", produits.IdLangue);
            return View(produits);
        }

        // GET: Produits/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Produits produits = db.Produits.Find(id);
            if (produits == null)
            {
                return HttpNotFound();
            }
            return View(produits);
        }

        // POST: Produits/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Produits produits = db.Produits.Find(id);
            db.Produits.Remove(produits);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult AfficherProduits(int? id, int? IdLangue)
        {
            string username = Session["username"].ToString();
            string password = Session["password"].ToString();

            var listLangue = db.Langues.ToList();
            ViewBag.Langue = listLangue;
            Session["IdCategorie"] = id;     
            if(IdLangue == 1)
            {
                return View((db.Produits.Where(m => m.IdCategorie == id && m.IdLangue == IdLangue).ToList()));
            }
            else
            {
                var listTraduction = db.ProduitsTraductions.Where(m => m.Categorie.IdCategorie == id && m.IdLangue == IdLangue).ToList();
                List<Produits> Produits = new List<Produits>();


                foreach (var traduction in listTraduction)
                {
                    Produits prod = new Produits();
                    prod.IdLangue = traduction.IdLangue;
                    prod.Nom = traduction.NomTraductions;
                    prod.Description = traduction.DescriptionTraductions;
                    prod.Prix = traduction.PrixTraductions;
                    prod.urlImage = traduction.urlImageTraductions;
                    prod.IdCategorie = traduction.IdCategorie;
                    Produits.Add(prod);

                }

                return View(Produits);
            }


        }


        public ActionResult VoirProduits(int ?id, int? IdLangue)
        {
            string username = Session["username"].ToString();
            string password = Session["password"].ToString();

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            return View(db.Produits.Where(p => p.IdProduits == id).ToList());


        }

        public ActionResult AjouterPanier(int id)
        {
            Produits produit = db.Produits.SingleOrDefault(m => m.IdProduits == id);
            string username = Session["username"].ToString();
            string password = Session["password"].ToString();

            Utilisateur utilisateur = db.Utilisateur.SingleOrDefault(m => m.Login.password == password & m.Login.username == username);

            Panier panier = new Panier { Produits = produit, Utilisateur = utilisateur };
            db.Paniers.Add(panier);
            db.SaveChanges();
            return RedirectToAction("Index", "Paniers");
        }






    }






    
}

Views/Produits/AfficherProduits.cshtml
@model IEnumerable<ProjetEpîcerie.Models.Produits>


<link href="~/Css/Acceuil.css" rel="stylesheet" />
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet">


<div id="langue">
    @if (ViewBag.Langue != null)
    {
        foreach (var lang in ViewBag.Langue)
        {
            <div class="lang-link">
                <a href="@Url.Action("AfficherProduits", "Produits", new { IdLangue = lang.IdLangue })">@lang.Symbole</a>
            </div>
        }

    }
</div>

<div id="carouselExample" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner py-4">
        <div class="carousel-item active">
            <div class="container">
                <div class="row">
                    @foreach (var element in Model)
                    {
                        <div class="col-lg-3 mb-4">
                            <div class="card my-custom-card">
                                <img src="@element.urlImage" class="card-img-top custom-card-image" alt="Waterfall" style="width:100%; height: 150px;">
                                <div class="card-body" style="width:100%; height: 320px;">
                                    <div style="width:100%; height:190px">
                                        <h5 class="card-title" id="titre1" style="font-weight:bold">@element.Nom</h5>
                                        <p class="card-text custom-card-text">@element.Description</p>

                                    </div>
                                    <p id="prix" style="font-weight:bold" >@element.Prix $CAD</p>

                                    <div class="boite2">
                                        @Html.ActionLink("Voir", "VoirProduits", new { id = @element.IdProduits, IdLangue = @element.IdLangue })
                                    </div>
                                    <div class="boite2">
                                        <div class="lang-link">
                                            @Html.ActionLink("Ajouter Panier", "AjouterPanier", new { id = @element.IdProduits, IdLangue = @element.IdLangue })
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>



<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

Views/Produits/AjouterPanier.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>AjouterPanier</title>
</head>
<body>
    <div> 
    </div>
</body>
</html>

Views/Produits/Create.cshtml
@model ProjetEpîcerie.Models.Produits

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Produits</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.IdLangue, "IdLangue", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdLangue", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdLangue, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdCategorie, "IdCategorie", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdCategorie", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdCategorie, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nom, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Prix, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Prix, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Prix, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.urlImage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.urlImage, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.urlImage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Views/Produits/Index.cshtml
@model IEnumerable<ProjetEpîcerie.Models.Produits>

<link href="~/Css/Acceuil.css" rel="stylesheet" />
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">

<header>
    <nav class="navbar navbar-expand-sm bg-white navbar-dark">
        <div class="container-fluid">

            <a class="navbar-brand" href="#">
                <img src="../image/logo3.jpg" alt="logo" style="width: 100px; height: auto;">
            </a>

            <span id="txtLogo" style="font-size:21px">  FARMERS MARKET </span>

            <div class="collapse navbar-collapse" id="collapsibleNavbar">
                <ul class="navbar-nav">
                    <li>
                        <a href="@Url.Action("Index", "Categories")" class="btn btn-primary">Catégories</a>
                    </li>
                    <li style="margin-left:10px">
                        <a href="@Url.Action("Index", "CategoriesTraductions")" class="btn btn-primary">Catégories Traductions</a>
                    </li>
                    <li style="margin-left:10px">
                        <a href="@Url.Action("Index", "Langues")" class="btn btn-primary"> Langues</a>
                    </li>
                    <li style="margin-left:10px">
                        <a href="@Url.Action("Index", "Paniers")" class="btn btn-primary"> Paniers</a>
                    </li>
                    <li style="margin-left:10px">
                        <a href="@Url.Action("Index", "Produits")" class="btn btn-primary"> Produits</a>
                    </li>
                    <li style="margin-left:10px">
                        <a href="@Url.Action("Index", "ProduitsTraductions")" class="btn btn-primary"> Produits Traductions</a>
                    </li>
                    <li style="margin-left:10px">
                        <a href="@Url.Action("Deconnexion", "Default")" class="btn btn-primary"> Deconnexion</a>
                    </li>

                </ul>

            </div>

        </div>
    </nav>
</header>
<div class="div1">
    <p class="titrePage">
        Liste des Produits
    </p>
</div>

<p>
    <a href="@Url.Action("Create", "Produits")"> Create new</a>
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Categorie.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Langue.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nom)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Prix)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.urlImage)
        </th>
        <th>
            Actions
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Categorie.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Langue.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nom)
            </td>
            <td colspan="4">
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Prix)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.urlImage)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.IdProduits }) |
                @Html.ActionLink("Details", "Details", new { id = item.IdProduits }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.IdProduits })
            </td>
        </tr>
    }

</table>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

Views/Produits/VoirProduits.cshtml
@model IEnumerable<ProjetEpîcerie.Models.Produits>


<link href="~/Css/Acceuil.css" rel="stylesheet" />
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet">
@{
    int idCategorie = Model.First().IdCategorie;//IdCategorie  du premier élément
}
@Html.Hidden("IdCategorie", idCategorie)


<div id="langue">
    @if (ViewBag.Langue != null)
    {
        foreach (var lang in ViewBag.Langue)
        {
            <div class="lang-link">
                <a href="@Url.Action("AfficherProduits", "Produits", new { id = lang.IdLangue })">@lang.Symbole</a>
            </div>
        }
    }
</div>

<div id="carouselExample" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner py-4">
        <div class="carousel-item active">
            <div class="container">
                <div class="row">
                    @foreach (var element in Model)
                    {
                        <div class="col-lg-3 mb-4">
                            <div class="card my-custom-card">
                                <img src="@element.urlImage" class="card-img-top custom-card-image" alt="Waterfall" style="width:100%; height: 150px;">
                                <div class="card-body" style="width:100%; height: 320px;">
                                    <div style="width:100%; height:190px">
                                        <h5 class="card-title" id="titre1" style="font-weight:bold">@element.Nom</h5>
                                        <p class="card-text custom-card-text">@element.Description</p>

                                    </div>
                                    <p id="prix" style="font-weight:bold">@element.Prix $CAD</p>
                                    <div class="boite2">
                                        <div class="lang-link">
                                            @Html.ActionLink("Ajouter Panier", "AjouterPanier", new { id = @element.IdProduits, IdLangue = @element.IdLangue })
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>



<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>